CREATE TABLE PLAYERS(
  ID string, 
  FIRSTNAME string, 
  LASTNAME string, 
  FIRSTSEASON int, 
  LASTSEASON int, 
  WEIGHT int, 
  BIRTHDATE date
);

SELECT EXPERIENCE, COUNT(ID) FROM (SELECT ID, FIRSTNAME, LASTNAME, (LASTSEASON -FIRSTSEASON) AS EXPERIENCE FROM PLAYERS) GROUP BY EXPERIENCE
SELECT FIRSTNAME, LASTNAME, WEIGHT, BIRTHDATE FROM PLAYERS WHERE WEIGHT>200
SELECT FIRSTNAME, LASTNAME, FIRSTSEASON, LASTSEASON FROM PLAYERS WHERE LASTSEASON - FIRSTSEASON > 5
